### ISSUE TITLE
Assignment3

### ISSUE THREAD

**Issue by AndreyIsakov01** [YatsenkoYura/HomeAssignments#3]
Выдает ошибку при сборке

**Comment by AndreyIsakov01** [comment]
1. get и set методы необходимы для всех полей базового класса
2. Завести отдельную цель test в Makefile для отдельной сборки тестов. Пример: https://github.com/vkats-spbu/gtest-demo.git

**Comment by YatsenkoYura** [comment]
Исправленно

**Comment by AndreyIsakov01** [comment]
1) Добавьте обязательный комментарий в каждый .cpp и .h файл
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/974537f8-4f98-45d5-8a92-ad1743742e3f" />

2) Перенесите реализации методов из заголовочного файла в соответствующий .cpp, иначе тяжело код читать

3) В названии get методов добавить слово get

4) Последний релиз g-test требует C++ 14. Поправьте при сборке
https://github.com/google/googletest?tab=readme-ov-file#release-1152

5) Добавьте общую цель для создания объектных файлов. Советую обратить внимание на пример:
https://github.com/vkats-spbu/gtest-demo/blob/main/Makefile
